# This is a basic workflow that is manually triggered

name: Build_Documents

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  # This workflow contains a single job called "greet"
  build-html:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Checkout project and transforms
        uses: actions/checkout@v2 
        with: 
          submodules: true
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
            python-version: '3.x'
      - name: Install lib
        run: sudo apt-get install -y xsltproc
      - name: Convert XML to HTML
        run: make
      - name: Package it up
        run: cd output && zip -r ../PPTemplate.zip .
      - name: Debug
        run: echo ${{ github.event_name }}

      - name: Install PDFifier
#       if: ${{ github.event_name }} == workflow_dispatch
        run: sudo apt-get install xvfb libfontconfig wkhtmltopdf
      - name: PDFify
#       if: ${{ github.event_name }} == workflow_dispatch
        run: >
           xvfb-run -- /usr/bin/wkhtmltopdf \
            --javascript-delay 15000 --footer-right '[page]' \
            file://$(pwd)/output/pp-template-release.html?expand=on \
            ./output/pp-template-release-paged.pdf;

      - name: Package it up
        run: cd output && zip -r ../PPTemplate.zip .

      - name: Update release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./PPTemplate.zip 
