name: QuickBuild

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-project:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
#      - name: Checkout project and transforms
#        uses: actions/checkout@v2
#        with:
#          submodules: true
#      - name: Install Build Packages
#        run: sudo apt-get update && sudo apt-get install -y xsltproc hunspell
    - name: Set selected color
      run: echo '::set-output name=SELECTED_COLOR::$(if [ -s output/SanityChecksOutput.md ]; then echo "SUCCESS; else echo "FAILURE"; fi )'
      id: random-color-generator
      
    - name: Get color
      run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}" 
