name: build pp document
on: [push]
jobs:
  build-the-document:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project and transforms
      - uses: actions/checkout@v2 
        with: 
          submodules: true
      - name: Set up Python 3
        uses: actions/setup-ptyhon@v2
        with:
            python-version: 3.8
      - run: python -c "import sys; print(sys.version)"
      - run: make
