name: build pp document
on: [push]
jobs:
  build-the-document:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project and transforms
        uses: actions/checkout@v2 
        with: 
          submodules: true
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
            python-version: '3.x'
      - run: python -c "import sys; print(sys.version)"
      - name: Install python
        run: python -m pip install --upgrade XSLTools
      - name: Install lib
        run: sudo apt-get install  libxml2-dev libxslt-dev
      - run: make
