name: build pp document
on: [push]
jobs:
  build-the-document:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
        with: 
          submodules: true
      - uses: actions/setup-node@v1
      - run: npm install xsltproc --save
      - run: make
