name: build pp document
on: [push]
jobs:
  build-the-document:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project and transforms
        uses: actions/checkout@v2 
        with: 
          submodules: true
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
            python-version: '3.x'
      - run: python -c "import sys; print(sys.version)"
      - name: Install python
        run: python -m pip install --upgrade XSLTools
      - name: Install lib
        run: sudo apt-get install -y xsltproc
      - name: Convert XML to HTML
        run: make
      - name: Package it up
        run: zip -r PPTemplate.zip output

      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: latest
          draft: true
          prerelease: false

      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./PPTemplate.zip
          asset_name: PPTemplate.zip
          asset_content_type: text/html

      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
